services:
  database:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-memevault}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-memevault}"]
      interval: 1s
      timeout: 1s
      retries: 5
    networks:
      - memevault-network

  image-storage:
    build:
      dockerfile: ./Dockerfile
      context: ../ImageStorage
    restart: always
    ports:
      - "80:8080"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-memevault}
      - SERVER_URL=:8080
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - memevault-network

  control-bot:
    build:
      dockerfile: ./Dockerfile
      context: ../MemeVaultControl
    restart: always
    environment:
      - Token=${TELEGRAM_BOT_TOKEN}
      - Endpoint=http://image-storage:8080
    depends_on:
      - image-storage
    networks:
      - memevault-network

volumes:
  pg_data:

networks:
  memevault-network:
    driver: bridge
