version: "3.9"

services:
  ai_video_description:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_video_description
    ports:
      - "5002:5000"
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1

    # Раскомментировать для использования GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: [gpu]

    volumes:
      - .:/app
